---
- name: Actualizar configuraciones de Proxy Inverso
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar contenido de /tmp/sites-available/ a /home/PruebaAnsible/sites-available/
      copy:
        src: "/tmp/sites-available/"
        dest: "/home/PruebaAnsible/sites-available/"
        remote_src: yes
