---
- name: Configuración de Dovecot
  hosts: servers_docker
  become: yes

  tasks:
    - name: Sincronizar contenido de la carpeta sites-available a /tmp
      copy:
        src: sites-available/
        dest: /tmp/sites-available
        recursive: yes

