---
- name: Configuración de Postfix
  hosts: servers_docker
  become: yes

  tasks:
    - name: Verificar el estado del archivo de configuración
      stat:
        path: /tmp/adminldap.red.hlg.sld.cu.conf
      register: config_stat

    - name: Copiar archivo de configuración de Postfix si ha cambiado
      copy:
        src: sites-available/adminldap.red.hlg.sld.cu.conf
        dest: /tmp/adminldap.red.hlg.sld.cu.conf
      when: config_stat.stat.ctime < config_stat.stat.mtime