---
- name: Configuración de Nginx
  hosts: servers_docker
  become: true

  tasks:
    - name: Clonar repositorio de configuración de Nginx
      ansible.builtin.git:
        repo: https://github.hlg.sld.cu/Nodo_Provincial/Proxy_Inverso1.git
        dest: /root/PruebaAnsible

    - name: Copiar archivos de configuración de Nginx
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/roles/nginx/files/sites-available/{{ item }}"
        dest: /ruta/remota/donde/quieres/guardar/{{ item }}
      loop:
        - adminldap.red.hlg.sld.cu.conf
        - adminldapcpicm.red.hlg.sld.cu.conf
      notify:
        - Reiniciar Nginx

  handlers:
    - name: Reiniciar Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
