---
- name: Actualizar configuraciones de Proxy Inverso
  hosts: servers_docker
  become: yes

  tasks:
    - name: Identificar archivos modificados en /tmp/sites-available/
      find:
        paths: "/tmp/sites-available/"
        patterns: "*"
      register: tmp_files

    - name: Copiar solo archivos modificados de /tmp/sites-available/ a /home/PruebaAnsible/sites-available/
      copy:
        src: "{{ item.path }}"
        dest: "/home/PruebaAnsible/sites-available/{{ item.path | basename }}"
      with_items: "{{ tmp_files.files }}"
      when: (item.path | basename) not in (current_files.files | map(attribute='path') | map('basename'))

    - name: Eliminar archivos locales que fueron eliminados en /tmp/sites-available/
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ current_files.files | difference(tmp_files.files) }}"
