---
- name: Actualizar configuraciones de Proxy Inverso
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar contenido de /tmp/sites-available/ a /home/PruebaAnsible/sites-available/
      copy:
        src: "/tmp/sites-available/"
        dest: "/home/PruebaAnsible/sites-available/"
        remote_src: yes

    - name: Identificar archivos en /home/PruebaAnsible/sites-available/ que deben eliminarse
      find:
        paths: "/home/PruebaAnsible/sites-available/"
        patterns: "*"
      register: current_files

    - name: Identificar archivos en /tmp/sites-available/
      find:
        paths: "/tmp/sites-available/"
        patterns: "*"
      register: tmp_files


