---
- name: Copiar archivo de configuración de Nginx
  hosts: tu_servidor
  become: true

  tasks:
    - name: Clonar solo el archivo necesario del repositorio
      ansible.builtin.git:
        repo: https://github.hlg.sld.cu/Nodo_Provincial/Proxy_Inverso1.git
        dest: /tmp
        clone: no

    - name: Copiar archivo de configuración
      ansible.builtin.copy:
        src: "/tmp/sites-available/adminldap.red.hlg.sld.cu.conf"
        dest: "/root/PruebaAnsible/adminldap.red.hlg.sld.cu.conf"
