- name: Copiar contenido de la carpeta sites-available al servidor Ngnix1
  hosts: all
#  become: yes
  vars:
    rsync_src: sites-available-rsync
    rsync_src_config: config
    rsync_dest: /home/PruebaAnsible/Rsync/sites-available/
    sites_available_path: /home/PruebaAnsible/Rsync/sites-available
    sites_enabled_path: /home/PruebaAnsible/Rsync/sites-enabled
    exclude_files: ['default', 'default-original', 'file2.conf']
    copy_config: true
    copy_other_config: true

  tasks:
    - name: Copiar carpeta usando rsync
      synchronize:
        src: "{{ rsync_src }}"
        dest: "{{ rsync_dest }}"
        delete: yes
        recursive: yes
        checksum: yes
        archive: no
        compress: yes
        times: yes
        rsync_opts:
          - "--exclude={{ exclude_files | join(' --exclude=') }}"

    - name: Verificar si nginx.conf existe en el repositorio
      stat:
        path: "{{ rsync_src_config }}/nginx.conf"
      register: nginx_conf

    - name: Copiar nginx.conf si existe en el repositorio y copy_config está activado
      copy:
        src: "{{ rsync_src_config }}/nginx.conf"
        dest: /home/PruebaAnsible/Rsync/nginx.conf
      when: nginx_conf.stat.exists and copy_config

    - name: Verificar si hay otros archivos de configuración en extras
      stat:
        path: "{{ rsync_src_config }}/extras"
      register: extras_config
      when: copy_other_config

    - name: Copiar otras configuraciones si copy_other_config está activado y existen archivos en extras
      synchronize:
        src: "{{ rsync_src_config }}/extras"
        dest: /home/PruebaAnsible/Rsync/
        recursive: yes
        rsync_opts:
          - "--exclude=nginx.conf"
      when: copy_other_config and extras_config.stat.exists
