- name: Copiar contenido de la carpeta sites-available al servidor Ngnix1
  hosts: all
#  become: yes

  tasks:
    - name: Copiar carpeta usando rsync
      synchronize:
        src: sites-available-rsync/
        dest: /home/PruebaAnsible/Rsync/sites-available/
        delete: yes
        recursive: yes
        checksum: yes
        archive: no
        compress: yes
        times: yes

    - name: Obtener la lista de archivos en sites-available
      find:
        paths: /home/PruebaAnsible/Rsync/sites-available
        patterns: "*"
      register: files_to_link

    - name: Crear enlaces simbólicos en sites-enabled
      file:
        src: "/home/PruebaAnsible/Rsync/sites-available/{{ item.path | basename }}"
        dest: "/home/PruebaAnsible/Rsync/sites-enabled/{{ item.path | basename }}"
        state: link
      with_items: "{{ files_to_link.files }}"	

    - name: Eliminar archivos locales que no existen en sites-available
      shell: "find /home/PruebaAnsible/Rsync/sites-available/ -type f -exec sh -c 'if [ ! -e \"/home/PruebaAnsible/Rsync/sites-enabled/$(basename {})\" ]; then rm -f {}; fi' \\;"