---
- name: Copiar archivo de configuración de Nginx
  hosts: servers_docker
  become: true

  tasks:
    - name: Clonar solo el archivo necesario del repositorio
      ansible.builtin.git:
        repo: https://github.hlg.sld.cu/Nodo_Provincial/Proxy_Inverso1.git
        dest: /tmp/semaphore/prueba
        clone: no

