- name: Copiar contenido de la carpeta sites-available al servidor Ngnix1
  hosts: all
#  become: yes
  vars:
    rsync_src: sites-available-rsync
    rsync_src_config: config
    rsync_dest: /home/PruebaAnsible/Rsync/sites-available/
    sites_available_path: /home/PruebaAnsible/Rsync/sites-available
    sites_enabled_path: /home/PruebaAnsible/Rsync/sites-enabled
    exclude_files: ['default', 'default-original', 'file2.conf']
    copy_config: true
    copy_other_config: true

  tasks:
    - name: Copiar carpeta usando rsync
      synchronize:
        src: "{{ rsync_src }}"
        dest: "{{ rsync_dest }}"
        delete: yes
        recursive: yes
        checksum: yes
        archive: no
        compress: yes
        times: yes
        rsync_opts:
          - "--exclude={{ exclude_files | join(' --exclude=') }}"

    - name: Copiar y reemplazar nginx.conf si copy_config está activado
      copy:
        src: "{{ rsync_src_config }}/nginx.conf"
        dest: /home/PruebaAnsible/Rsync/nginx.conf
      when: copy_config
      register: copy_nginx_conf_result
      failed_when: copy_nginx_conf_result is failed and not 'No such file or directory' in copy_nginx_conf_result.msg

    - name: Copiar otras configuraciones si copy_other_config está activado
      synchronize:
        src: "{{ rsync_src_config }}/extras"
        dest: /home/PruebaAnsible/Rsync/
        recursive: yes
        rsync_opts:
          - "--exclude=nginx.conf"
      when: copy_other_config
      register: copy_extras_result
      failed_when: copy_extras_result is failed and not 'No such file or directory' in copy_extras_result.msg
