---
- name: Actualizar configuraciones de Proxy Inverso
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar contenido de /tmp/sites-available/ a /home/PruebaAnsible/sites-available/
      shell: "cp -r /tmp/sites-available/* /home/PruebaAnsible/sites-available/"

    - name: Eliminar archivos locales que fueron eliminados en /tmp/sites-available/
      shell: "comm -23 <(ls /home/PruebaAnsible/sites-available/ | sort) <(ls /tmp/sites-available/ | sort) | xargs -I {} rm -f /home/PruebaAnsible/sites-available/{}"
