- name: Copiar contenido de la carpeta sites-available al servidor Nginx1
  hosts: all
  vars:
    rsync_src: sites-available/
    rsync_dest: /home/PruebaAnsible/sites-available/
    sites_available_path: /home/PruebaAnsible/sites-available
    sites_enabled_path: /home/PruebaAnsible/sites-enabled

  tasks:
    - name: Copiar carpeta usando rsync
      synchronize:
        src: "{{ rsync_src }}"
        dest: "{{ rsync_dest }}"
        delete: yes
        recursive: yes
        checksum: yes
        archive: no
        compress: yes
        times: yes
        rsync_opts:
          - "--exclude=default"

    - name: Obtener la lista de archivos en sites-available
      find:
        paths: "{{ sites_available_path }}"
        patterns: "*"
      register: files_to_link

    - name: Crear enlaces simbólicos en sites-enabled
      file:
        src: "{{ sites_available_path }}/{{ item.path | basename }}"
        dest: "{{ sites_enabled_path }}/{{ item.path | basename }}"
        state: link
      when: not item.path | basename | regex_search('-off$')
      with_items: "{{ files_to_link.files }}"

