- name: Copiar contenido de la carpeta sites-available al servidor Ngnix1
  hosts: Server_Local_Docker
  become: yes

  tasks:
    - name: Copiar carpeta usando rsync
      synchronize:
        src: sites-available-rsync/
        dest: /home/PruebaAnsible/Rsync/sites-available
        delete: yes
        recursive: yes
        checksum: yes
        archive: yes
        compress: yes

    - name: Crear enlaces simbólicos en sites-enabled
      file:
        src: /home/PruebaAnsible/Rsync/sites-available/{{ item }}
        dest: /home/PruebaAnsible/Rsync/sites-enabled/{{ item }}
        state: link
      loop: "{{ lookup('fileglob', '/home/PruebaAnsible/Rsync/sites-available/*') | basename }}"
      notify: Reiniciar Nginx

#  handlers:
#    - name: Reiniciar Nginx
#      service:
#        name: nginx
#        state: restarted

