---
- name: Eliminar archivos locales que no existen en el repositorio
  hosts: servers_docker
  become: yes

  tasks:
    - name: Obtener la lista de archivos en sites-available del repositorio
      find:
        paths: sites-available/
        patterns: "*"
      register: repo_files

    - name: Eliminar archivos locales que no existen en el repositorio
      file:
        path: "/home/PruebaAnsible/sites-available/{{ item.path | basename }}"
        state: absent
      loop: "{{ lookup('fileglob', '/home/PruebaAnsible/sites-available/*') }}"
      when: not (repo_files.files | map(attribute='path') | any == "/home/PruebaAnsible/sites-available/{{ item.path | basename }}")