---
- name: Eliminar archivos locales eliminados en el repositorio remoto
  hosts: servers_docker
  become: yes

  tasks:
    - name: Obtener la lista de archivos en sites-available del repositorio remoto
      find:
        paths: sites-available/
        patterns: "*"
      register: local_files

    - name: Eliminar archivos locales que no existen en el repositorio
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ local_files.files }}"
      when: "'/home/PruebaAnsible/sites-available/' + item.path | basename not in semaphore_git_files.files | map(attribute='path') | map('regex_replace', '$', '')"
