---
- name: Configuración de Proxy Inverso 1
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar contenido de la carpeta sites-available al servidor Ngnix1
      copy:
        src: sites-available/
        dest: /tmp/sites-available/

    - name: Copiar contenido de /tmp/sites-available/ a /home/PruebaAnsible/sites-available/
      shell: "cp -R /tmp/sites-available/* /home/PruebaAnsible/sites-available/"

#    - shell: rm -R /tmp/sites-available
 