---
- name: Configuración de Dovecot
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar archivo de configuración 
      copy:
        src: sites-available/adminldap.red.hlg.sld.cu.conf
        dest: /tmp
