---
- name: Configuración de Proxy Inverso 1
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar contenido de la carpeta sites-available al servidor Ngnix1
      copy:
        src: sites-available/
        dest: /tmp/sites-available/

 