---
- name: Clonar repositorio en servidor local
  hosts: localhost
  tasks:
    - name: Clonar el repositorio
      ansible.builtin.git:
        repo: https://github.hlg.sld.cu/Nodo_Provincial/Proxy_Inverso1.git
        dest: /tmp/semaphore/prueba

