- name: Copiar contenido de la carpeta sites-available al servidor Nginx1
  hosts: all
#  become: yes
  vars:
    rsync_src: sites-available-rsync/
    rsync_dest: /home/PruebaAnsible/Rsync/sites-available/
    sites_available_path: /home/PruebaAnsible/Rsync/sites-available
    sites_enabled_path: /home/PruebaAnsible/Rsync/sites-enabled
    exclude_files: ('default' 'file1.conf' 'file2.conf')

  tasks:
    - name: Copiar carpeta usando rsync
      synchronize:
        src: sites-available-rsync/
        dest: /home/PruebaAnsible/Rsync/sites-available/
        delete: yes
        recursive: yes
        checksum: yes
        archive: no
        compress: yes
        times: yes

    - name: Obtener la lista de archivos en sites-available
      find:
        paths: /home/PruebaAnsible/Rsync/sites-available
        patterns: "*"
      register: files_to_link

    - name: Eliminar enlaces simbólicos para archivos renombrados con -off
      file:
        path: "/home/PruebaAnsible/Rsync/sites-enabled/{{ item.path | basename | regex_replace('-off$', '') }}"
        state: absent
      when: item.path | basename | regex_search('-off$')
      with_items: "{{ files_to_link.files }}"

    - name: Crear enlaces simbólicos en sites-enabled
      file:
        src: "/home/PruebaAnsible/Rsync/sites-available/{{ item.path | basename }}"
        dest: "/home/PruebaAnsible/Rsync/sites-enabled/{{ item.path | basename }}"
        state: link
      when: not item.path | basename | regex_search('-off$')
      with_items: "{{ files_to_link.files }}"

