---
- name: Actualizar configuraciones de Proxy Inverso
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar contenido de /tmp/sites-available/ a /home/PruebaAnsible/sites-available/
      copy:
        src: "/tmp/sites-available/"
        dest: "/home/PruebaAnsible/sites-available/"
        remote_src: yes

    - name: Eliminar archivos locales que no existen en /tmp/sites-available/
      find:
        paths: "/home/PruebaAnsible/sites-available/"
        patterns: "*"
      register: local_files

    - name: Verificar archivos en /tmp/sites-available/
      find:
        paths: "/tmp/sites-available/"
        patterns: "*"
      register: tmp_files

    - name: Eliminar archivos locales que no existen en /tmp/sites-available/
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ local_files.files | rejectattr('path', 'in', tmp_files.files | map(attribute='path')) }}"
