---
- name: Configuración de Dovecot
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar contenido de la carpeta sites-available a /tmp
      copy:
        src: sites-available/
        dest: /tmp/
      notify:
        - Reiniciar Dovecot

