---
- name: Copiar contenido de la carpeta sites-available al servidor Ngnix1
  hosts: Server_Local_Docker
  become: yes

  tasks:
    - name: Copiar carpeta usando rsync
      synchronize:
        src: sites-available-rsync/
        dest: /home/PruebaAnsible/Rsync/
