---
- name: Actualizar configuraciones de Proxy Inverso
  hosts: servers_docker
  become: yes

  tasks:
    - name: Copiar contenido de /tmp/sites-available/ a /home/PruebaAnsible/sites-available/
      shell: "cp -R /tmp/sites-available/* /home/PruebaAnsible/sites-available/"

    - name: Eliminar archivos locales que no existen en /tmp/sites-available/
      shell: "find /home/PruebaAnsible/sites-available/ -type f -exec sh -c 'if [ ! -e \"/tmp/sites-available/$(basename {})\" ]; then rm -f {}; fi' \\;"
